name: talvori
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.2
  font_awesome_flutter: ^10.10.0
  fluentui_system_icons: ^1.1.273
  flutter_svg: ^2.2.1
  image_picker: ^1.0.7
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.6.0
  share_handler: ^0.0.21
  http: ^1.2.2
  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
